"""empty message

Revision ID: 8ae577057c30
Revises: 86da08e335b7
Create Date: 2024-07-15 11:23:15.609363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ae577057c30'
down_revision = '86da08e335b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patrons', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    with op.batch_alter_table('youths', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('youths', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('patrons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
