"""Removed Columns.

Revision ID: e08e41686e3c
Revises: 1f54022ec57c
Create Date: 2024-07-15 07:43:23.179848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e08e41686e3c'
down_revision = '1f54022ec57c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('youth_id')

    with op.batch_alter_table('youths', schema=None) as batch_op:
        batch_op.drop_constraint('fk_youths_game_id_games', type_='foreignkey')
        batch_op.drop_column('game_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('youths', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_youths_game_id_games', 'games', ['game_id'], ['id'])

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('youth_id', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
